# Generated by Django 5.2.5 on 2025-08-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='案件名')),
                ('description', models.TextField(blank=True, verbose_name='案件概要')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='バジェット側担当者')),
                ('assigned_user', models.CharField(blank=True, max_length=100, verbose_name='担当ユーザー')),
                ('target_industry', models.CharField(blank=True, max_length=100, verbose_name='ターゲット業界')),
                ('target_company_size', models.CharField(blank=True, max_length=50, verbose_name='ターゲット企業規模')),
                ('dm_template', models.TextField(blank=True, verbose_name='DMテンプレート')),
                ('status', models.CharField(choices=[('進行中', '進行中'), ('完了', '完了'), ('中止', '中止')], default='進行中', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了予定日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='clients.client', verbose_name='クライアント')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NGImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='ファイル名')),
                ('imported_count', models.IntegerField(default=0, verbose_name='インポート総数')),
                ('matched_count', models.IntegerField(default=0, verbose_name='マッチした数')),
                ('unmatched_count', models.IntegerField(default=0, verbose_name='マッチしなかった数')),
                ('imported_by', models.CharField(blank=True, max_length=100, verbose_name='インポート実行者')),
                ('error_messages', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='クライアント')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': 'NGリストインポート履歴',
                'verbose_name_plural': 'NGリストインポート履歴',
                'db_table': 'ng_import_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('未接触', '未接触'), ('DM送信予定', 'DM送信予定'), ('DM送信済み', 'DM送信済み'), ('返信あり', '返信あり'), ('アポ獲得', 'アポ獲得'), ('成約', '成約'), ('NG', 'NG')], default='未接触', max_length=20, verbose_name='営業ステータス')),
                ('contact_date', models.DateField(blank=True, null=True, verbose_name='最終接触日')),
                ('staff_name', models.CharField(blank=True, max_length=100, verbose_name='担当者')),
                ('notes', models.TextField(blank=True, verbose_name='個別メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_companies', to='companies.company', verbose_name='企業')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_companies', to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件企業',
                'verbose_name_plural': '案件企業',
                'db_table': 'project_companies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNGCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='NG理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ng_projects', to='companies.company', verbose_name='企業')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ng_companies', to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件NG企業',
                'verbose_name_plural': '案件NG企業',
                'db_table': 'project_ng_companies',
            },
        ),
        migrations.CreateModel(
            name='RandomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='ユーザーID')),
                ('session_id', models.CharField(blank=True, max_length=255, verbose_name='セッションID')),
                ('filter_hash', models.CharField(max_length=64, verbose_name='フィルタハッシュ')),
                ('company_ids_order', models.JSONField(default=list, verbose_name='企業ID表示順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': 'ランダム表示順序',
                'verbose_name_plural': 'ランダム表示順序',
                'db_table': 'random_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='ユーザーID')),
                ('name', models.CharField(max_length=100, verbose_name='フィルタ名')),
                ('filter_conditions', models.JSONField(verbose_name='検索条件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '保存済みフィルタ',
                'verbose_name_plural': '保存済みフィルタ',
                'db_table': 'saved_filters',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='saved_filte_user_id_408d55_idx'), models.Index(fields=['name'], name='saved_filte_name_d778f9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client'], name='projects_client__90eb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='projects_name_3fb8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_created_40bcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ngimportlog',
            index=models.Index(fields=['client'], name='ng_import_l_client__9f61a8_idx'),
        ),
        migrations.AddIndex(
            model_name='ngimportlog',
            index=models.Index(fields=['project'], name='ng_import_l_project_c36e33_idx'),
        ),
        migrations.AddIndex(
            model_name='ngimportlog',
            index=models.Index(fields=['created_at'], name='ng_import_l_created_77a47c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcompany',
            index=models.Index(fields=['project'], name='project_com_project_9abcec_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcompany',
            index=models.Index(fields=['company'], name='project_com_company_95b668_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcompany',
            index=models.Index(fields=['status'], name='project_com_status_4046ff_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcompany',
            index=models.Index(fields=['contact_date'], name='project_com_contact_131c46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcompany',
            unique_together={('project', 'company')},
        ),
        migrations.AddIndex(
            model_name='projectngcompany',
            index=models.Index(fields=['project'], name='project_ng__project_f244de_idx'),
        ),
        migrations.AddIndex(
            model_name='projectngcompany',
            index=models.Index(fields=['company'], name='project_ng__company_eccbbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectngcompany',
            unique_together={('project', 'company')},
        ),
        migrations.AddIndex(
            model_name='randomorder',
            index=models.Index(fields=['session_id'], name='random_orde_session_13e6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='randomorder',
            index=models.Index(fields=['filter_hash'], name='random_orde_filter__9b4970_idx'),
        ),
        migrations.AddIndex(
            model_name='randomorder',
            index=models.Index(fields=['project'], name='random_orde_project_1ad922_idx'),
        ),
    ]
