# Generated by Django 5.2.5 on 2025-08-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcompany',
            name='appointment_count',
            field=models.IntegerField(default=0, verbose_name='アポ獲得数'),
        ),
        migrations.AddField(
            model_name='projectcompany',
            name='appointment_result',
            field=models.CharField(blank=True, choices=[('成約', '成約'), ('継続検討', '継続検討'), ('見送り', '見送り')], max_length=20, verbose_name='アポ結果'),
        ),
        migrations.AddField(
            model_name='projectcompany',
            name='last_appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='最終アポ日'),
        ),
    ]
