# Generated by Django 5.2.5 on 2025-09-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sales_history_expansion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saleshistory',
            new_name='sales_histo_project_5dc7cb_idx',
            old_name='sales_history_project_company_idx',
        ),
        migrations.RenameIndex(
            model_name='saleshistory',
            new_name='sales_histo_status_25e163_idx',
            old_name='sales_history_status_idx',
        ),
        migrations.RenameIndex(
            model_name='saleshistory',
            new_name='sales_histo_status__27785c_idx',
            old_name='sales_history_status_date_idx',
        ),
    ]
