# Generated by Django 5.2.5 on 2025-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_sales_history_project_company_idx_sales_histo_project_5dc7cb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcompany',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アクティブ状態'),
        ),
    ]
