# Generated by Django 5.2.5 on 2025-09-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_listavailability_listimportsource_mediatype_and_more'),
        ('projects', '0005_projectcompany_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='account_link',
            field=models.URLField(blank=True, verbose_name='アカウントリンク'),
        ),
        migrations.AddField(
            model_name='project',
            name='appointment_count',
            field=models.IntegerField(default=0, verbose_name='アポ数'),
        ),
        migrations.AddField(
            model_name='project',
            name='approval_count',
            field=models.IntegerField(default=0, verbose_name='承認数'),
        ),
        migrations.AddField(
            model_name='project',
            name='assignment_available',
            field=models.BooleanField(default=True, verbose_name='アサイン可否'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_ng_operational_barriers',
            field=models.TextField(blank=True, verbose_name='クライアントNG、運用障壁'),
        ),
        migrations.AddField(
            model_name='project',
            name='complaints_requests',
            field=models.TextField(blank=True, verbose_name='クレームor要望（20%上回ったものを最優先処理）'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='連絡先'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_period',
            field=models.CharField(blank=True, max_length=100, verbose_name='契約期間'),
        ),
        migrations.AddField(
            model_name='project',
            name='daily_tasks',
            field=models.TextField(blank=True, verbose_name='デイリータスク(当日行うべき業務を記載)'),
        ),
        migrations.AddField(
            model_name='project',
            name='director',
            field=models.CharField(blank=True, max_length=100, verbose_name='ディレクター'),
        ),
        migrations.AddField(
            model_name='project',
            name='director_login_available',
            field=models.BooleanField(default=False, verbose_name='Dがログインできるアカウント'),
        ),
        migrations.AddField(
            model_name='project',
            name='entry_date_sales',
            field=models.DateField(blank=True, null=True, verbose_name='記載日(営業)'),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了予定日'),
        ),
        migrations.AddField(
            model_name='project',
            name='friends_count',
            field=models.IntegerField(default=0, verbose_name='友達数'),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='業種'),
        ),
        migrations.AddField(
            model_name='project',
            name='issues_improvements',
            field=models.TextField(blank=True, verbose_name='課題点＋改善点'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.listavailability', verbose_name='リスト有無'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_count',
            field=models.IntegerField(default=0, verbose_name='リスト数'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_import_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.listimportsource', verbose_name='リスト輸入先'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_prefecture',
            field=models.CharField(blank=True, max_length=10, verbose_name='所在地(都道府県)'),
        ),
        migrations.AddField(
            model_name='project',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.mediatype', verbose_name='媒体'),
        ),
        migrations.AddField(
            model_name='project',
            name='operation_sheet_link',
            field=models.URLField(blank=True, verbose_name='運用シートリンク'),
        ),
        migrations.AddField(
            model_name='project',
            name='operation_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='運用開始日'),
        ),
        migrations.AddField(
            model_name='project',
            name='operator',
            field=models.CharField(blank=True, max_length=100, verbose_name='運用者'),
        ),
        migrations.AddField(
            model_name='project',
            name='operator_group_invited',
            field=models.BooleanField(default=False, verbose_name='運用者グループ招待'),
        ),
        migrations.AddField(
            model_name='project',
            name='period_extension',
            field=models.CharField(blank=True, max_length=100, verbose_name='期間延期'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.projectprogressstatus', verbose_name='進行状況'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_tasks',
            field=models.TextField(blank=True, verbose_name='進行タスク・ネクストタスク・期限'),
        ),
        migrations.AddField(
            model_name='project',
            name='regular_meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='定例会実施日'),
        ),
        migrations.AddField(
            model_name='project',
            name='regular_meeting_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.regularmeetingstatus', verbose_name='定例会提示'),
        ),
        migrations.AddField(
            model_name='project',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備考(現在の状態について記載)'),
        ),
        migrations.AddField(
            model_name='project',
            name='reply_check_notes',
            field=models.TextField(blank=True, verbose_name='返信チェック(伊藤が朝消す)'),
        ),
        migrations.AddField(
            model_name='project',
            name='reply_count',
            field=models.IntegerField(default=0, verbose_name='返信数'),
        ),
        migrations.AddField(
            model_name='project',
            name='report_link',
            field=models.URLField(blank=True, verbose_name='レポートリンク'),
        ),
        migrations.AddField(
            model_name='project',
            name='restrictions',
            field=models.TextField(blank=True, verbose_name='制限'),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='営業マン'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.servicetype', verbose_name='サービス'),
        ),
        migrations.AddField(
            model_name='project',
            name='situation',
            field=models.TextField(blank=True, verbose_name='状況'),
        ),
        migrations.CreateModel(
            name='ProjectEditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='ロック開始日時')),
                ('expires_at', models.DateTimeField(verbose_name='ロック期限')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_lock', to='projects.project', verbose_name='案件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='編集中ユーザー')),
            ],
            options={
                'verbose_name': '案件編集ロック',
                'verbose_name_plural': '案件編集ロック',
                'db_table': 'project_edit_locks',
                'indexes': [models.Index(fields=['project'], name='project_edi_project_5bd9ed_idx'), models.Index(fields=['user'], name='project_edi_user_id_14a66a_idx'), models.Index(fields=['expires_at'], name='project_edi_expires_75e80e_idx')],
            },
        ),
    ]
