# Generated by Django 5.2.5 on 2025-09-19 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_account_link_project_appointment_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='ページ番号')),
                ('page_size', models.IntegerField(default=20, verbose_name='ページサイズ')),
                ('filter_hash', models.CharField(blank=True, max_length=64, verbose_name='フィルタハッシュ')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='ロック開始日時')),
                ('expires_at', models.DateTimeField(verbose_name='ロック期限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='編集中ユーザー')),
            ],
            options={
                'verbose_name': 'ページ編集ロック',
                'verbose_name_plural': 'ページ編集ロック',
                'db_table': 'page_edit_locks',
                'indexes': [models.Index(fields=['user'], name='page_edit_l_user_id_601379_idx'), models.Index(fields=['page_number'], name='page_edit_l_page_nu_3ee411_idx'), models.Index(fields=['expires_at'], name='page_edit_l_expires_d8d5b2_idx'), models.Index(fields=['filter_hash'], name='page_edit_l_filter__fa81f2_idx')],
                'unique_together': {('page_number', 'filter_hash')},
            },
        ),
    ]
