# Generated by Django 5.2.5 on 2025-09-20 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_pageeditlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='スナップショットデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='理由')),
                ('source', models.CharField(choices=[('bulk_edit', '一括編集'), ('undo', '取り消し'), ('restore', '復元')], default='bulk_edit', max_length=50, verbose_name='生成元')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件スナップショット',
                'verbose_name_plural': '案件スナップショット',
                'db_table': 'project_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='project_sna_project_4aa036_idx')],
            },
        ),
    ]
