# Generated by Django 5.2.5 on 2025-08-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='業界名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '業界',
                'verbose_name_plural': '業界',
                'db_table': 'industries',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='industries_name_285c10_idx'), models.Index(fields=['is_active'], name='industries_is_acti_0792b5_idx'), models.Index(fields=['display_order'], name='industries_display_9f45f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ステータス名')),
                ('category', models.CharField(choices=[('company', '企業'), ('project', '案件'), ('contact', '営業')], max_length=20, verbose_name='カテゴリ')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('color_code', models.CharField(blank=True, max_length=7, verbose_name='表示色')),
                ('description', models.TextField(blank=True, verbose_name='ステータス説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ステータス',
                'verbose_name_plural': 'ステータス',
                'db_table': 'statuses',
                'ordering': ['category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['category'], name='statuses_categor_5046d4_idx'), models.Index(fields=['name'], name='statuses_name_c46494_idx'), models.Index(fields=['is_active'], name='statuses_is_acti_3f81ca_idx'), models.Index(fields=['display_order'], name='statuses_display_1f876b_idx')],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
