# Generated by Django 5.2.5 on 2025-08-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='都道府県名')),
                ('region', models.CharField(max_length=10, verbose_name='地方区分')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
                'db_table': 'prefectures',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='prefectures_name_097fbe_idx'), models.Index(fields=['region'], name='prefectures_region_b6628c_idx'), models.Index(fields=['display_order'], name='prefectures_display_b0ea60_idx')],
            },
        ),
    ]
