# Generated by Django 5.2.5 on 2025-09-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_prefecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='リスト有無名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'リスト有無',
                'verbose_name_plural': 'リスト有無',
                'db_table': 'list_availabilities',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='list_availa_name_269322_idx'), models.Index(fields=['is_active'], name='list_availa_is_acti_ac66f8_idx'), models.Index(fields=['display_order'], name='list_availa_display_6e28f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='リスト輸入先名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'リスト輸入先',
                'verbose_name_plural': 'リスト輸入先',
                'db_table': 'list_import_sources',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='list_import_name_f93d69_idx'), models.Index(fields=['is_active'], name='list_import_is_acti_7f7742_idx'), models.Index(fields=['display_order'], name='list_import_display_859759_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='媒体名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '媒体',
                'verbose_name_plural': '媒体',
                'db_table': 'media_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='media_types_name_82adea_idx'), models.Index(fields=['is_active'], name='media_types_is_acti_ec3cd0_idx'), models.Index(fields=['display_order'], name='media_types_display_b543eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='進行状況名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('color_code', models.CharField(blank=True, max_length=7, verbose_name='表示色')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '案件進行状況',
                'verbose_name_plural': '案件進行状況',
                'db_table': 'project_progress_statuses',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='project_pro_name_bd7915_idx'), models.Index(fields=['is_active'], name='project_pro_is_acti_d7fe60_idx'), models.Index(fields=['display_order'], name='project_pro_display_00930b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegularMeetingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='定例会ステータス名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '定例会ステータス',
                'verbose_name_plural': '定例会ステータス',
                'db_table': 'regular_meeting_statuses',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='regular_mee_name_fe67fa_idx'), models.Index(fields=['is_active'], name='regular_mee_is_acti_8d1081_idx'), models.Index(fields=['display_order'], name='regular_mee_display_2ee421_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='サービス名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サービス',
                'verbose_name_plural': 'サービス',
                'db_table': 'service_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='service_typ_name_42c743_idx'), models.Index(fields=['is_active'], name='service_typ_is_acti_5307ae_idx'), models.Index(fields=['display_order'], name='service_typ_display_c23cde_idx')],
            },
        ),
    ]
