# Generated by Django 5.2.5 on 2025-09-07 08:52

from django.db import migrations


def create_initial_data(apps, schema_editor):
    """マスターデータの初期データを作成"""
    ProjectProgressStatus = apps.get_model('masters', 'ProjectProgressStatus')
    RegularMeetingStatus = apps.get_model('masters', 'RegularMeetingStatus')
    ListAvailability = apps.get_model('masters', 'ListAvailability')
    ListImportSource = apps.get_model('masters', 'ListImportSource')
    
    # 進行状況マスター（設計書に基づく）
    progress_statuses = [
        ('未着手', 1),
        ('ヒアリングシート記入中', 2),
        ('キックオフMTG', 3),
        ('DM作成・確認/アカウント構築', 4),
        ('リスト作成中', 5),
        ('運用者アサイン中', 6),
        ('運用中', 7),
        ('停止', 8),
        ('解釈', 9),
        ('一時停止', 10),
        ('契約満了', 11),
        ('開始時期未定・変更', 12),
        ('解体', 13),
        ('営業追いかけ', 14),
    ]
    
    # 定例会ステータスマスター（設計書に基づく）
    meeting_statuses = [
        ('未', 1),
        ('済', 2),
        ('不要', 3),
        ('20日未満', 4),
        ('未開始', 5),
        ('最終定例会予定', 6),
    ]
    
    # リスト有無マスター（設計書に基づく）
    list_availabilities = [
        ('無', 1),
        ('有（我々提供）', 2),
        ('有（クライアント提供）', 3),
    ]
    
    # リスト輸入先マスター（設計書に基づく）
    import_sources = [
        ('インフォボックス', 1),
        ('セールスナビゲーター', 2),
        ('バジェットリスト', 3),
        ('返信ありから', 4),
        ('その他', 5),
        ('無', 6),
    ]
    
    # データ作成
    for name, order in progress_statuses:
        ProjectProgressStatus.objects.get_or_create(
            name=name,
            defaults={
                'display_order': order,
                'is_active': True,
            }
        )
    
    for name, order in meeting_statuses:
        RegularMeetingStatus.objects.get_or_create(
            name=name,
            defaults={
                'display_order': order,
                'is_active': True,
            }
        )
    
    for name, order in list_availabilities:
        ListAvailability.objects.get_or_create(
            name=name,
            defaults={
                'display_order': order,
                'is_active': True,
            }
        )
    
    for name, order in import_sources:
        ListImportSource.objects.get_or_create(
            name=name,
            defaults={
                'display_order': order,
                'is_active': True,
            }
        )
    
    # サービスマスター（追記）
    ServiceType = apps.get_model('masters', 'ServiceType')
    service_types = [
        ('アウトソーシング', 1), ('SNS運用代行', 2), ('広告代理店', 3), ('SEO', 4), ('HP制作', 5),
        ('Web制作', 6), ('Webマーケ', 7), ('人材派遣', 8), ('人材紹介', 9), ('採用支援', 10),
        ('SES', 11), ('BPO', 12), ('店舗', 13), ('営業代行', 14), ('テレアポ', 15),
        ('アポ獲得', 16), ('M&A仲介', 17), ('経営', 18), ('助成金', 19), ('リスキリング', 20),
        ('人材教育', 21), ('社内教育', 22), ('賃貸', 23), ('売買', 24), ('アプリ開発', 25),
        ('Web開発', 26), ('SaaS', 27), ('Sier', 28), ('経営者コミュニティ', 29), ('オンラインサロン', 30),
        ('交流会', 31), ('芸能', 32), ('引っ越し', 33), ('建設', 34), ('動画制作', 35),
        ('エンタメ', 36), ('資産運用', 37), ('EC', 38), ('LINE構築', 39), ('AI', 40),
        ('トレカ販売', 41), ('フランチャイズ', 42), ('アート', 43), ('HP掲載', 44),
    ]
    
    for name, order in service_types:
        ServiceType.objects.get_or_create(
            name=name,
            defaults={
                'display_order': order,
                'is_active': True,
            }
        )


def reverse_initial_data(apps, schema_editor):
    """初期データを削除"""
    ProjectProgressStatus = apps.get_model('masters', 'ProjectProgressStatus')
    RegularMeetingStatus = apps.get_model('masters', 'RegularMeetingStatus')
    ListAvailability = apps.get_model('masters', 'ListAvailability')
    ListImportSource = apps.get_model('masters', 'ListImportSource')
    ServiceType = apps.get_model('masters', 'ServiceType')
    
    ProjectProgressStatus.objects.all().delete()
    RegularMeetingStatus.objects.all().delete()
    ListAvailability.objects.all().delete()
    ListImportSource.objects.all().delete()
    ServiceType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_listavailability_listimportsource_mediatype_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
