# Generated by Django 5.0.7 on 2025-12-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_industry_hierarchy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='industry',
            new_name='industries_parent__477cef_idx',
            old_name='industries_parent__idx',
        ),
        migrations.RenameIndex(
            model_name='industry',
            new_name='industries_is_cate_f47f69_idx',
            old_name='industries_is_cate_idx',
        ),
    ]
