# Generated by Django 5.2.5 on 2025-08-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='顧客企業名')),
                ('company_type', models.CharField(blank=True, max_length=50, verbose_name='企業タイプ')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='顧客の業界')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='連絡先メール')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='連絡先電話')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('website', models.URLField(blank=True, verbose_name='ウェブサイト')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'クライアント',
                'verbose_name_plural': 'クライアント',
                'db_table': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='clients_name_0bc5f0_idx'), models.Index(fields=['is_active'], name='clients_is_acti_43299d_idx'), models.Index(fields=['industry'], name='clients_industr_cdecff_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientNGCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='企業名')),
                ('matched', models.BooleanField(default=False, verbose_name='マッチ状態')),
                ('reason', models.TextField(blank=True, verbose_name='NG理由')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ng_companies', to='clients.client', verbose_name='クライアント')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='マッチした企業')),
            ],
            options={
                'verbose_name': 'クライアントNG企業',
                'verbose_name_plural': 'クライアントNG企業',
                'db_table': 'client_ng_companies',
                'indexes': [models.Index(fields=['client'], name='client_ng_c_client__cef7e9_idx'), models.Index(fields=['company_name'], name='client_ng_c_company_9deb17_idx'), models.Index(fields=['company'], name='client_ng_c_company_f3e1bf_idx'), models.Index(fields=['matched'], name='client_ng_c_matched_592afe_idx')],
                'unique_together': {('client', 'company_name')},
            },
        ),
    ]
