version: '3.8'

services:
  # App Run #3: PostgreSQL Database
  database:
    build: ./database
    container_name: social-navigator-database-dev
    environment:
      POSTGRES_DB: social_navigator
      POSTGRES_USER: social_navigator_user
      POSTGRES_PASSWORD: social_navigator_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - social-navigator-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_navigator_user -d social_navigator"]
      interval: 10s
      timeout: 5s
      retries: 5

  # App Run #2: Django Backend (ホットリロード対応)
  backend:
    build: ../
    container_name: social-navigator-backend-dev
    environment:
      - DATABASE_URL=postgresql://social_navigator_user:social_navigator_password@database:5432/social_navigator
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=social_navigator
      - DB_USER=social_navigator_user
      - DB_PASSWORD=social_navigator_password
      - DEBUG=True
      - SECRET_KEY=django-local-development-key-not-for-production
      - CORS_ALLOW_ALL_ORIGINS=True
    ports:
      - "8080:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - social-navigator-network
    volumes:
      - ../:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python seed_data.py &&
        python manage.py runserver 0.0.0.0:8000
      "

  # App Run #1: Next.js Frontend (ホットリロード対応)
  frontend:
    build:
      context: ../../saleslist-front
      dockerfile: Dockerfile.dev
    container_name: social-navigator-frontend-dev
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api/v1
      - NODE_ENV=development
    ports:
      - "3002:3000"
    volumes:
      - ../../saleslist-front:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - social-navigator-network
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:

networks:
  social-navigator-network:
    driver: bridge