# 自治体オープンデータ ソース定義
# 収集ハンドラ (local_gov_open_data_<pref>) が参照する設定ファイル。
# 各エントリはダウンロードURL / ファイル形式 / 文字コード / 列マッピングを含む。

sources:
  tokyo_corporate_members:
    label: "東京都 法人会員企業一覧"
    url: "https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000055/resource/2b860a90-1fad-4a43-b257-09cd7fadc558/download/csv.zip"
    format: zip_csv
    encoding: shift_jis
    delimiter: ","
    source_detail: local_gov_open_data_tokyo
    mappings:
      corporate_number: "法人番号"
      name: "商号又は名称"
      postal_code: "郵便番号"
      address: "所在地"
      capital_stock: "資本金"
      industry: "業種"
      website_url: "URL"

  shizuoka_company_db:
    label: "静岡県 企業情報データベース"
    url: "https://open-data.pref.shizuoka.jp/dataset/kachikachi/data/202410_company_list.csv"
    format: csv
    encoding: utf-8
    delimiter: ","
    source_detail: local_gov_open_data_shizuoka
    mappings:
      corporate_number: "法人番号"
      name: "企業名"
      address: "所在地"
      industry: "業種"
      employee_size: "従業員数"
      website_url: "URL"
      phone_number: "電話番号"

  osaka_sm_support:
    label: "大阪府 中小企業サポート企業情報"
    url: "https://data.city.osaka.lg.jp/api/download/resourceId/0000091234"
    format: csv
    encoding: utf-8
    delimiter: ","
    source_detail: local_gov_open_data_osaka
    mappings:
      corporate_number: "法人番号"
      name: "企業名"
      address: "所在地"
      capital_stock: "資本金"
      employee_size: "従業員数"
      industry_code: "業種コード"
      industry: "業種名"
      website_url: "URL"
      phone_number: "電話番号"

# 住所の正規化や電話番号のハイフン除去は ingestion 側で実施する。
# URL は candidate_value に正規化した値を入れ、metadata.original_url で元データを保持する。
