# Generated by Django 5.2.5 on 2025-08-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='企業名')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='業界')),
                ('employee_count', models.IntegerField(blank=True, null=True, verbose_name='従業員数')),
                ('revenue', models.BigIntegerField(blank=True, null=True, verbose_name='売上高')),
                ('prefecture', models.CharField(blank=True, max_length=10, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='市区町村')),
                ('established_year', models.IntegerField(blank=True, null=True, verbose_name='設立年')),
                ('website_url', models.URLField(blank=True, max_length=500, verbose_name='ウェブサイト')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='連絡先メール')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_global_ng', models.BooleanField(default=False, verbose_name='グローバルNG設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '企業',
                'verbose_name_plural': '企業',
                'db_table': 'companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='companies_name_c7a1b3_idx'), models.Index(fields=['industry'], name='companies_industr_7891ac_idx'), models.Index(fields=['prefecture'], name='companies_prefect_1f4c57_idx'), models.Index(fields=['employee_count'], name='companies_employe_d2a4fd_idx'), models.Index(fields=['is_global_ng'], name='companies_is_glob_00e126_idx'), models.Index(fields=['created_at'], name='companies_created_c84a3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='役員名')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('facebook_url', models.URLField(blank=True, max_length=500, verbose_name='Facebook URL')),
                ('other_sns_url', models.URLField(blank=True, max_length=500, verbose_name='その他SNS URL')),
                ('direct_email', models.EmailField(blank=True, max_length=254, verbose_name='直接メール')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='companies.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': '役員',
                'verbose_name_plural': '役員',
                'db_table': 'executives',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='executives_company_e2960d_idx'), models.Index(fields=['name'], name='executives_name_c363a7_idx'), models.Index(condition=models.Q(('facebook_url__isnull', False)), fields=['facebook_url'], name='executives_facebook_url_idx')],
            },
        ),
    ]
