# Generated by Django 5.2.5 on 2025-08-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_description',
            field=models.TextField(blank=True, verbose_name='事業内容'),
        ),
        migrations.AddField(
            model_name='company',
            name='capital',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='資本金'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='担当者役職'),
        ),
        migrations.AddField(
            model_name='company',
            name='corporate_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='法人番号'),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Facebookリンク'),
        ),
        migrations.AddField(
            model_name='company',
            name='tob_toc_type',
            field=models.CharField(blank=True, choices=[('toB', 'toB'), ('toC', 'toC'), ('Both', 'Both')], max_length=10, verbose_name='toB/toC'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在地詳細'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='業種'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='売上規模'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='会社HP'),
        ),
    ]
