# Generated by Django 5.2.5 on 2025-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_review_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyupdatecandidate',
            name='block_reproposal',
            field=models.BooleanField(default=False, verbose_name='再提案ブロック'),
        ),
        migrations.AddField(
            model_name='companyupdatecandidate',
            name='rejection_reason_code',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '指定なし'),
                    ('mismatch_company', '同名別会社'),
                    ('invalid_value', '不正値'),
                    ('outdated', '古い情報'),
                    ('duplicate', '重複'),
                    ('other', 'その他'),
                ],
                default='',
                max_length=32,
                verbose_name='否認理由コード',
            ),
        ),
        migrations.AddField(
            model_name='companyupdatecandidate',
            name='rejection_reason_detail',
            field=models.TextField(blank=True, verbose_name='否認理由詳細'),
        ),
        migrations.AddField(
            model_name='companyupdatecandidate',
            name='source_company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ソース企業名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyupdatecandidate',
            name='source_corporate_number',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='ソース法人番号'),
            preserve_default=False,
        ),
    ]

