# Generated by Django 5.0.7 on 2025-10-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companyupdatecandidate_reproposal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='対象フィールド')),
                ('source', models.CharField(max_length=100, verbose_name='ソースID')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='最終取得日時')),
                ('data_hash', models.CharField(blank=True, max_length=128, verbose_name='データハッシュ')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_source_records', to='companies.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': '外部データ取得履歴',
                'verbose_name_plural': '外部データ取得履歴',
                'db_table': 'company_external_source_records',
                'unique_together': {('company', 'field', 'source')},
            },
        ),
    ]
