# Generated by Django 5.0.7 on 2025-10-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_externalsourcerecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='companies_latest__9a7066_idx',
            old_name='companies_latest_activity_idx',
        ),
        migrations.RenameIndex(
            model_name='companyfacebooksnapshot',
            new_name='company_fac_company_516196_idx',
            old_name='company_facebook_snapshots_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='companyreviewbatch',
            new_name='company_rev_status_a3cefd_idx',
            old_name='company_re_status_67a29a_idx',
        ),
        migrations.RenameIndex(
            model_name='companyreviewbatch',
            new_name='company_rev_company_137cec_idx',
            old_name='company_re_company_4d93a7_idx',
        ),
        migrations.RenameIndex(
            model_name='companyreviewitem',
            new_name='company_rev_batch_i_ec51b0_idx',
            old_name='company_re_batch_i_62b0ee_idx',
        ),
        migrations.RenameIndex(
            model_name='companyreviewitem',
            new_name='company_rev_decisio_f3c22f_idx',
            old_name='company_re_decisio_0b7ffb_idx',
        ),
        migrations.RenameIndex(
            model_name='companyupdatecandidate',
            new_name='company_upd_company_e5d0e6_idx',
            old_name='company_upd_company_575986_idx',
        ),
        migrations.RenameIndex(
            model_name='companyupdatecandidate',
            new_name='company_upd_status_44f622_idx',
            old_name='company_upd_status_d6483b_idx',
        ),
        migrations.RenameIndex(
            model_name='companyupdatecandidate',
            new_name='company_upd_source__08d607_idx',
            old_name='company_upd_source__fc818a_idx',
        ),
        migrations.RenameIndex(
            model_name='companyupdatehistory',
            new_name='company_upd_company_bb9ec3_idx',
            old_name='company_upd_company_a908b8_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyfacebooksnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalsourcerecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='companyupdatecandidate',
            index=models.Index(fields=['value_hash'], name='company_upd_value_h_ad1384_idx'),
        ),
    ]
