# Generated by Django 5.0.7 on 2025-10-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_rename_companies_latest_activity_idx_companies_latest__9a7066_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_last_enriched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI最終補完日時'),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_last_enriched_source',
            field=models.CharField(blank=True, max_length=32, verbose_name='AI補完ソース'),
        ),
    ]
