# Generated by Django 5.0.7 on 2025-10-30 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_name', models.CharField(db_index=True, max_length=64)),
                ('data_source', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, default='QUEUED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('input_count', models.IntegerField(default=0)),
                ('inserted_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('skip_breakdown', models.JSONField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('next_scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Collection Run',
                'verbose_name_plural': 'Data Collection Runs',
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['job_name', '-started_at'], name='data_collec_job_nam_417fd8_idx')],
            },
        ),
    ]
