openapi: 3.0.3
info:
  title: プロジェクト管理API拡張
  description: インライン編集・排他制御機能付きプロジェクト管理API
  version: 1.0.0

paths:
  /projects/:
    get:
      tags:
      - Projects
      summary: 案件一覧取得（編集モード対応）
      description: 一覧画面表示用の案件データとロック状態を取得
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          default: 1
      - name: limit
        in: query
        schema:
          type: integer
          default: 20
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 50
                  next:
                    type: string
                    nullable: true
                    example: "http://localhost:8006/api/v1/projects/?page=3"
                  previous:
                    type: string
                    nullable: true
                    example: "http://localhost:8006/api/v1/projects/?page=1"
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProjectListItem'

  /projects/{id}/:
    get:
      tags:
      - Projects
      summary: 案件詳細取得
      description: 詳細画面表示用の全項目データを取得
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetailItem'
        404:
          description: 案件が見つかりません
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "案件が見つかりません"

    patch:
      tags:
      - Projects
      summary: 案件更新（インライン編集）
      description: 一覧画面での編集可能項目のみ更新
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectUpdateRequest'
      responses:
        200:
          description: 更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/ProjectListItem'
        400:
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: object
        403:
          description: 他のユーザーが編集中
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "この案件は田中太郎が編集中です"
                  locked_by_name:
                    type: string
                    example: "田中太郎"

  /projects/{id}/lock/:
    post:
      tags:
      - Projects
      summary: 編集ロック取得
      description: 案件の編集権を取得する
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        200:
          description: ロック取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  locked_until:
                    type: string
                    format: date-time
                    example: "2024-01-01T12:30:00Z"
        409:
          description: 既に他のユーザーがロック中
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "この案件は田中太郎が編集中です"
                  locked_by_name:
                    type: string
                    example: "田中太郎"
                  locked_until:
                    type: string
                    format: date-time
                    example: "2024-01-01T12:30:00Z"

    delete:
      tags:
      - Projects
      summary: 編集ロック解除
      description: 案件の編集権を解除する
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        200:
          description: ロック解除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        403:
          description: 他のユーザーのロックは解除できない
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "このロックは解除できません"

  /master/progress-statuses/:
    get:
      tags:
      - Master
      summary: 進行状況マスター取得
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MasterData'

  /master/media-types/:
    get:
      tags:
      - Master
      summary: 媒体マスター取得
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MasterData'

components:
  schemas:
    ProjectListItem:
      type: object
      description: 一覧画面表示用プロジェクトデータ
      properties:
        id:
          type: integer
          example: 1
        client_name:
          type: string
          example: "テスト企業"
        progress_status:
          type: string
          example: "運用中"
        director_login_available:
          type: boolean
          example: true
        operator_group_invited:
          type: boolean
          example: false
        appointment_count:
          type: integer
          example: 5
        approval_count:
          type: integer
          example: 3
        reply_count:
          type: integer
          example: 8
        friends_count:
          type: integer
          example: 15
        situation:
          type: string
          example: "順調に進行中"
        is_locked:
          type: boolean
          example: false
        locked_by:
          type: integer
          nullable: true
          example: null
        locked_by_name:
          type: string
          nullable: true
          example: null
        locked_until:
          type: string
          format: date-time
          nullable: true
          example: null
        created_at:
          type: string
          format: date-time
          example: "2024-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2024-01-01T00:00:00Z"

    ProjectDetailItem:
      type: object
      description: 詳細画面表示用プロジェクトデータ（全項目）
      properties:
        id:
          type: integer
          example: 1
        client_name:
          type: string
          example: "テスト企業"
        location_prefecture:
          type: string
          example: "東京都"
        industry:
          type: string
          example: "IT・ソフトウェア"
        service_type:
          type: string
          example: "Facebook営業代行"
        # リンク情報
        operation_sheet_link:
          type: string
          example: "https://docs.google.com/spreadsheets/d/xxx"
        report_link:
          type: string
          example: "https://docs.google.com/document/d/xxx"
        account_link:
          type: string
          example: "https://facebook.com/account"
        # 媒体・制限情報
        media_type:
          type: string
          example: "Facebook"
        restrictions:
          type: string
          example: "特になし"
        contact_info:
          type: string
          example: "田中太郎 03-1234-5678"
        # 数値データ
        appointment_count:
          type: integer
          example: 5
        approval_count:
          type: integer
          example: 3
        reply_count:
          type: integer
          example: 8
        friends_count:
          type: integer
          example: 15
        # 状況・進行管理
        situation:
          type: string
          example: "順調に進行中"
        progress_status:
          type: string
          example: "運用中"
        # チェック・タスク管理
        reply_check_notes:
          type: string
          example: "毎朝9時にチェック"
        daily_tasks:
          type: string
          example: "メッセージ送信10件"
        progress_tasks:
          type: string
          example: "レポート作成（来週まで）"
        remarks:
          type: string
          example: "クライアント満足度高い"
        complaints_requests:
          type: string
          example: "特になし"
        # NG・課題管理
        client_ng_operational_barriers:
          type: string
          example: "特定業界は除外"
        issues_improvements:
          type: string
          example: "返信率向上が課題"
        # 担当者情報
        director:
          type: string
          example: "山田太郎"
        operator:
          type: string
          example: "佐藤花子"
        sales_person:
          type: string
          example: "田中次郎"
        assignment_available:
          type: boolean
          example: true
        # チェックボックス項目
        director_login_available:
          type: boolean
          example: true
        operator_group_invited:
          type: boolean
          example: false
        # 契約・期間情報
        contract_period:
          type: string
          example: "3ヶ月"
        entry_date_sales:
          type: string
          format: date
          example: "2024-01-01"
        operation_start_date:
          type: string
          format: date
          example: "2024-01-15"
        expected_end_date:
          type: string
          format: date
          example: "2024-04-15"
        period_extension:
          type: string
          example: "1ヶ月延長"
        # 定例会情報
        regular_meeting_status:
          type: string
          example: "済"
        regular_meeting_date:
          type: string
          format: date
          example: "2024-01-20"
        # リスト情報
        list_availability:
          type: string
          example: "有（我々提供）"
        list_import_source:
          type: string
          example: "ソーシャルナビゲーター"
        list_count:
          type: integer
          example: 1000
        # システム管理
        created_at:
          type: string
          format: date-time
          example: "2024-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2024-01-01T00:00:00Z"

    ProjectUpdateRequest:
      type: object
      description: 案件更新リクエスト（一覧画面編集項目のみ）
      properties:
        director_login_available:
          type: boolean
          example: true
        operator_group_invited:
          type: boolean
          example: false
        progress_status:
          type: string
          example: "運用中"
        appointment_count:
          type: integer
          minimum: 0
          example: 6
        approval_count:
          type: integer
          minimum: 0
          example: 4
        reply_count:
          type: integer
          minimum: 0
          example: 9
        friends_count:
          type: integer
          minimum: 0
          example: 16
        situation:
          type: string
          maxLength: 1000
          example: "更新された状況"

    ProjectDetailUpdateRequest:
      type: object
      description: 案件更新リクエスト（詳細画面全項目）
      properties:
        client_name:
          type: string
          example: "テスト企業"
        location_prefecture:
          type: string
          example: "東京都"
        industry:
          type: string
          example: "IT・ソフトウェア"
        service_type:
          type: string
          example: "Facebook営業代行"
        operation_sheet_link:
          type: string
          example: "https://docs.google.com/spreadsheets/d/xxx"
        report_link:
          type: string
          example: "https://docs.google.com/document/d/xxx"
        account_link:
          type: string
          example: "https://facebook.com/account"
        media_type:
          type: string
          example: "Facebook"
        restrictions:
          type: string
          example: "特になし"
        contact_info:
          type: string
          example: "田中太郎 03-1234-5678"
        appointment_count:
          type: integer
          minimum: 0
          example: 6
        approval_count:
          type: integer
          minimum: 0
          example: 4
        reply_count:
          type: integer
          minimum: 0
          example: 9
        friends_count:
          type: integer
          minimum: 0
          example: 16
        situation:
          type: string
          example: "更新された状況"
        progress_status:
          type: string
          example: "運用中"
        reply_check_notes:
          type: string
          example: "毎朝9時にチェック"
        daily_tasks:
          type: string
          example: "メッセージ送信10件"
        progress_tasks:
          type: string
          example: "レポート作成（来週まで）"
        remarks:
          type: string
          example: "クライアント満足度高い"
        complaints_requests:
          type: string
          example: "特になし"
        client_ng_operational_barriers:
          type: string
          example: "特定業界は除外"
        issues_improvements:
          type: string
          example: "返信率向上が課題"
        director:
          type: string
          example: "山田太郎"
        operator:
          type: string
          example: "佐藤花子"
        sales_person:
          type: string
          example: "田中次郎"
        assignment_available:
          type: boolean
          example: true
        director_login_available:
          type: boolean
          example: true
        operator_group_invited:
          type: boolean
          example: false
        contract_period:
          type: string
          example: "3ヶ月"
        entry_date_sales:
          type: string
          format: date
          example: "2024-01-01"
        operation_start_date:
          type: string
          format: date
          example: "2024-01-15"
        expected_end_date:
          type: string
          format: date
          example: "2024-04-15"
        period_extension:
          type: string
          example: "1ヶ月延長"
        regular_meeting_status:
          type: string
          example: "済"
        regular_meeting_date:
          type: string
          format: date
          example: "2024-01-20"
        list_availability:
          type: string
          example: "有（我々提供）"
        list_import_source:
          type: string
          example: "ソーシャルナビゲーター"
        list_count:
          type: integer
          minimum: 0
          example: 1000

    MasterData:
      type: object
      description: マスターデータ
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "運用中"
        display_order:
          type: integer
          example: 1
        is_active:
          type: boolean
          example: true

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
- bearerAuth: []
